version: '3.8'

services:
  django_atlantis_dark:
    build: './django-atlantis-dark'
    container_name: django-atlantis-dark
    restart: always

  django_argon_dashboard:
    build: './django-argon-dashboard'
    container_name: django-argon-dashboard
    restart: always

  django_soft_ui_dashboard:
    build: './django-soft-ui-dashboard'
    container_name: django-soft-ui-dashboard
    restart: always

  django_adminlte:
    build: './django-adminlte'
    container_name: django-adminlte
    restart: always

  django_modernize:
    build: './django-modernize'
    container_name: django-modernize
    restart: always

  flask_material_dashboard:
    build: './flask-material-dashboard'
    container_name: flask-material-dashboard
    restart: always
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine-slim
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
    volumes:
      - ./nginx:/etc/nginx/conf.d

volumes:
  postgres_data:
